(*
  TropicalPoly.thy -- tropical polynomials are convex; tropical rational functions.

  A tropical monomial is c odot x1^a1 odot ... = (an affine function with the given
  slopes and constant). A tropical POLYNOMIAL is a tropical sum (= pointwise max) of
  monomials, optionally with tropical products (= pointwise sums) -- the inductive
  class `troppoly` below, closed under affine, +, and max. Because each generator is
  convex and convexity is preserved by + and by max, every tropical polynomial is a
  CONVEX function (troppoly_convex) -- the geometric heart of the theory: tropical
  polynomials are exactly the convex piecewise-linear functions.

  A tropical RATIONAL function is a tropical quotient f oslash g = f - g of two
  tropical polynomials (troprat). These are exactly the (not necessarily convex)
  continuous piecewise-linear functions; ReLU networks live here (ReLUNet.thy).

  Maps to Zhang-Naitzat-Lim Def 2.4 (tropical rational function) and the convexity of
  tropical polynomials.
*)

theory TropicalPoly
  imports "HOL-Analysis.Analysis" TropicalSemiring
begin

text \<open>A tropical monomial -- an affine function -- is convex (indeed affine).\<close>

lemma convex_on_affine:
  fixes a :: "'a::real_inner"
  shows "convex_on UNIV (\<lambda>x. inner a x + c)"
proof (rule convex_onI)
  fix t :: real and x y :: 'a
  assume "0 < t" "t < 1"
  have "inner a ((1 - t) *\<^sub>R x + t *\<^sub>R y) = (1 - t) * inner a x + t * inner a y"
    by (simp add: inner_add_right inner_scaleR_right)
  thus "inner a ((1 - t) *\<^sub>R x + t *\<^sub>R y) + c \<le> (1 - t) * (inner a x + c) + t * (inner a y + c)"
    by (simp add: algebra_simps)
next
  show "convex UNIV" by simp
qed

text \<open>The pointwise max of two convex functions is convex (tropical addition
  preserves convexity). No such lemma is in the library; we prove it directly.\<close>

lemma convex_on_max:
  assumes "convex_on A f" "convex_on A g"
  shows "convex_on A (\<lambda>x. max (f x) (g x))"
proof (rule convex_onI)
  fix t :: real and x y
  assume t: "0 < t" "t < 1" and xy: "x \<in> A" "y \<in> A"
  have tt: "0 \<le> t" "0 \<le> 1 - t" using t by auto
  have fz: "f ((1 - t) *\<^sub>R x + t *\<^sub>R y) \<le> (1 - t) * f x + t * f y"
    using convex_onD[OF assms(1)] t xy by auto
  have gz: "g ((1 - t) *\<^sub>R x + t *\<^sub>R y) \<le> (1 - t) * g x + t * g y"
    using convex_onD[OF assms(2)] t xy by auto
  have "(1 - t) * f x + t * f y \<le> (1 - t) * max (f x) (g x) + t * max (f y) (g y)"
    using tt by (intro add_mono mult_left_mono) auto
  moreover have "(1 - t) * g x + t * g y \<le> (1 - t) * max (f x) (g x) + t * max (f y) (g y)"
    using tt by (intro add_mono mult_left_mono) auto
  ultimately show "max (f ((1 - t) *\<^sub>R x + t *\<^sub>R y)) (g ((1 - t) *\<^sub>R x + t *\<^sub>R y))
                    \<le> (1 - t) * max (f x) (g x) + t * max (f y) (g y)"
    using fz gz by auto
next
  show "convex A" using assms(1) by (rule convex_on_imp_convex)
qed

text \<open>Tropical polynomials: the inductive class generated by affine monomials and
  closed under tropical sum (max) and tropical product (+).\<close>

inductive troppoly :: "('a::real_inner \<Rightarrow> real) \<Rightarrow> bool" where
  affine: "troppoly (\<lambda>x. inner a x + c)"
| add:    "troppoly f \<Longrightarrow> troppoly g \<Longrightarrow> troppoly (\<lambda>x. f x + g x)"
| maxp:   "troppoly f \<Longrightarrow> troppoly g \<Longrightarrow> troppoly (\<lambda>x. max (f x) (g x))"

text \<open>Every tropical polynomial is a convex function.\<close>

theorem troppoly_convex: "troppoly f \<Longrightarrow> convex_on UNIV f"
proof (induction rule: troppoly.induct)
  case (affine a c) show ?case by (rule convex_on_affine)
next
  case (add f g) thus ?case by (simp add: convex_on_add)
next
  case (maxp f g)
  then have a: "convex_on UNIV f" and b: "convex_on UNIV g" by blast+
  show ?case by (rule convex_on_max[OF a b])
qed

lemma troppoly_const: "troppoly (\<lambda>x. c)"
  using troppoly.affine[of 0 c] by simp

text \<open>Tropical polynomials are closed under non-negative scaling (a non-negative
  tropical-scalar multiple of a tropical polynomial is a tropical polynomial).\<close>

lemma troppoly_scale_nonneg:
  assumes "troppoly f" "0 \<le> c"
  shows "troppoly (\<lambda>x. c * f x)"
  using assms(1)
proof (induction rule: troppoly.induct)
  case (affine a d)
  have eq: "(\<lambda>x::'a. c * (inner a x + d)) = (\<lambda>x. inner (c *\<^sub>R a) x + c * d)"
    by (simp add: fun_eq_iff inner_scaleR_left algebra_simps)
  show ?case unfolding eq by (rule troppoly.affine)
next
  case (add f g)
  have eq: "(\<lambda>x. c * (f x + g x)) = (\<lambda>x. c * f x + c * g x)"
    by (simp add: fun_eq_iff algebra_simps)
  have "troppoly (\<lambda>x. c * f x + c * g x)" using add.IH by (rule troppoly.add)
  thus ?case unfolding eq .
next
  case (maxp f g)
  have pt: "c * max (f x) (g x) = max (c * f x) (c * g x)" for x
  proof (cases "f x \<le> g x")
    case True
    have "c * f x \<le> c * g x" by (rule mult_left_mono[OF True assms(2)])
    thus ?thesis using True by (simp add: max_def)
  next
    case False
    hence "g x \<le> f x" by simp
    hence "c * g x \<le> c * f x" by (rule mult_left_mono[OF _ assms(2)])
    thus ?thesis using False by (simp add: max_def)
  qed
  have eq: "(\<lambda>x. c * max (f x) (g x)) = (\<lambda>x. max (c * f x) (c * g x))"
    using pt by (simp add: fun_eq_iff)
  have "troppoly (\<lambda>x. max (c * f x) (c * g x))" using maxp.IH by (rule troppoly.maxp)
  thus ?case unfolding eq .
qed

text \<open>A tropical rational function is a tropical quotient of two tropical
  polynomials: pointwise, the difference of two convex piecewise-linear functions.\<close>

definition troprat :: "('a::real_inner \<Rightarrow> real) \<Rightarrow> bool" where
  "troprat f \<longleftrightarrow> (\<exists>g h. troppoly g \<and> troppoly h \<and> (\<forall>x. f x = g x - h x))"

lemma troppoly_imp_troprat: "troppoly f \<Longrightarrow> troprat f"
  unfolding troprat_def
  by (intro exI[of _ f] exI[of _ "\<lambda>x. 0"]) (simp add: troppoly_const)

lemma troprat_affine: "troprat (\<lambda>x. inner a x + c)"
  by (rule troppoly_imp_troprat[OF troppoly.affine])

lemma troprat_const: "troprat (\<lambda>x. c)"
  by (rule troppoly_imp_troprat[OF troppoly_const])

end
